# Generated by Django 5.1.7 on 2025-03-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=255)),
                ('student_email', models.EmailField(default='default@default.com', max_length=254)),
                ('personal_email', models.EmailField(max_length=254, null=True)),
                ('locker_number', models.IntegerField(default=1)),
                ('locker_combination', models.CharField(default='default')),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
