# Generated by Django 5.1.7 on 2025-03-27 01:00

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(validators=[subject_app.validators.validate_professor_name]),
        ),
    ]
